#https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: ASDF ubuntu, Ubuntu Node

# Controls when the action will run.
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      dockerhub_repo:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

env:
  #*.ub = Build node is Ubuntu
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.dockerhub_repo }}
            ${{ env.REGISTRY }}/${{ inputs.image_name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # https://github.com/docker/scout-cli#github-action
      # - name: Docker Scout
      #   id: docker-scout
      #   # if: ${{ github.event_name == 'pull_request' }}
      #   uses: docker/scout-action@dd36f5b0295baffa006aa6623371f226cc03e506
      #   with:
      #     command: cves
      #     image: ${{ steps.meta.outputs.tags }}
      #     only-severities: critical,high
      #     exit-code: true
