name: linksCheck

on:
  workflow_call:
    inputs:
      file-path:
        required: true
        type: string

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        # checks all markdown files from /docs including all subfolders
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".github/workflows/markdown.links.config.json"
          file-path: ${{ inputs.file-path }}
